# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reminders_pb2 as reminders__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in reminders_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ReminderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddReminder = channel.unary_unary(
                '/ReminderService/AddReminder',
                request_serializer=reminders__pb2.Reminder.SerializeToString,
                response_deserializer=reminders__pb2.Reminder.FromString,
                _registered_method=True)
        self.GetAll = channel.unary_unary(
                '/ReminderService/GetAll',
                request_serializer=reminders__pb2.Empty.SerializeToString,
                response_deserializer=reminders__pb2.ReminderList.FromString,
                _registered_method=True)
        self.GetReminder = channel.unary_unary(
                '/ReminderService/GetReminder',
                request_serializer=reminders__pb2.ReminderTitle.SerializeToString,
                response_deserializer=reminders__pb2.Reminder.FromString,
                _registered_method=True)
        self.UpdateReminder = channel.unary_unary(
                '/ReminderService/UpdateReminder',
                request_serializer=reminders__pb2.Reminder.SerializeToString,
                response_deserializer=reminders__pb2.Reminder.FromString,
                _registered_method=True)
        self.DeleteReminder = channel.unary_unary(
                '/ReminderService/DeleteReminder',
                request_serializer=reminders__pb2.ReminderId.SerializeToString,
                response_deserializer=reminders__pb2.Empty.FromString,
                _registered_method=True)


class ReminderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddReminder(self, request, context):
        """CRUD Database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReminder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReminder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReminder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReminderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddReminder': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReminder,
                    request_deserializer=reminders__pb2.Reminder.FromString,
                    response_serializer=reminders__pb2.Reminder.SerializeToString,
            ),
            'GetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=reminders__pb2.Empty.FromString,
                    response_serializer=reminders__pb2.ReminderList.SerializeToString,
            ),
            'GetReminder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReminder,
                    request_deserializer=reminders__pb2.ReminderTitle.FromString,
                    response_serializer=reminders__pb2.Reminder.SerializeToString,
            ),
            'UpdateReminder': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReminder,
                    request_deserializer=reminders__pb2.Reminder.FromString,
                    response_serializer=reminders__pb2.Reminder.SerializeToString,
            ),
            'DeleteReminder': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReminder,
                    request_deserializer=reminders__pb2.ReminderId.FromString,
                    response_serializer=reminders__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReminderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReminderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddReminder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReminderService/AddReminder',
            reminders__pb2.Reminder.SerializeToString,
            reminders__pb2.Reminder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReminderService/GetAll',
            reminders__pb2.Empty.SerializeToString,
            reminders__pb2.ReminderList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReminder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReminderService/GetReminder',
            reminders__pb2.ReminderTitle.SerializeToString,
            reminders__pb2.Reminder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateReminder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReminderService/UpdateReminder',
            reminders__pb2.Reminder.SerializeToString,
            reminders__pb2.Reminder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReminder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReminderService/DeleteReminder',
            reminders__pb2.ReminderId.SerializeToString,
            reminders__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
