# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reminders.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freminders.proto\"\\\n\x08Reminder\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x11\n\tdeskripsi\x18\x05 \x01(\t\",\n\x0cReminderList\x12\x1c\n\treminders\x18\x01 \x03(\x0b\x32\t.Reminder\"\x1e\n\rReminderTitle\x12\r\n\x05title\x18\x01 \x01(\t\"\x18\n\nReminderId\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xda\x01\n\x0fReminderService\x12%\n\x0b\x41\x64\x64Reminder\x12\t.Reminder\x1a\t.Reminder\"\x00\x12!\n\x06GetAll\x12\x06.Empty\x1a\r.ReminderList\"\x00\x12*\n\x0bGetReminder\x12\x0e.ReminderTitle\x1a\t.Reminder\"\x00\x12(\n\x0eUpdateReminder\x12\t.Reminder\x1a\t.Reminder\"\x00\x12\'\n\x0e\x44\x65leteReminder\x12\x0b.ReminderId\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reminders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REMINDER']._serialized_start=19
  _globals['_REMINDER']._serialized_end=111
  _globals['_REMINDERLIST']._serialized_start=113
  _globals['_REMINDERLIST']._serialized_end=157
  _globals['_REMINDERTITLE']._serialized_start=159
  _globals['_REMINDERTITLE']._serialized_end=189
  _globals['_REMINDERID']._serialized_start=191
  _globals['_REMINDERID']._serialized_end=215
  _globals['_EMPTY']._serialized_start=217
  _globals['_EMPTY']._serialized_end=224
  _globals['_REMINDERSERVICE']._serialized_start=227
  _globals['_REMINDERSERVICE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
